[style] 할 일 리스트 View Layout
weekFlex/Cartier pull request #12
Opened 2021-03-24 09:04 UTC by xwoud

## Task 내용  
- [x] 할 일 리스트 View 레이아웃 완료
- [x] 할 일이 1가지 이상 선택 -> 다음 버튼 활성화
- [x] 처음 뷰에 들어왔을 때 첫번째 카테고리 자동 선택
- [x] 할 일 검색 시 : 라인 컬러 변경 및 카테고리 선택 무효화 후 검색어에 맞는 할 일을 필터링해 보여줌
- [x] 할 일을 검색하다 카테고리를 선택 시 : 검색어는 제거된 후, 카테고리에 맞는 할 일 보여줌
- [x] 할 일 클릭 시 : 루틴에 추가된 후, 배경이 회색으로 바뀜 ( 하지만 이미 루틴에 추가됐는데 한번 더 누른다면 아무 일 X )
- [x] 루틴 추가 시 : 루틴 이름 길이에 맞게 cell size 조절
- [x] 추가된 루틴을 지울 시 : 추가된 목록에서 삭제된 후, 리스트에서 회색 배경이 제거됨
- [x] 카테고리 밑에 그림자 추가

## 관계된 이슈, PR :  
#3 

### 기기별 스크린 샷
iphone12Pro | iphone12mini | iphoneSE  |
:---: | :---: | :---:
<img width="250" src="https://user-images.githubusercontent.com/51286963/112282541-8fdf7180-8cca-11eb-93bc-563e5f234cc3.png"> | <img width="250" src="https://user-images.githubusercontent.com/51286963/112282572-953cbc00-8cca-11eb-8117-76d52a0f9875.png"> | <img width="250" src="https://user-images.githubusercontent.com/51286963/112282580-966de900-8cca-11eb-82fc-ffbddb467818.png">

### 경우 별 스크린샷
ex. 데이터가 있을 때 | 없을 때 
:---: | :---: 
<img width="250" src="https://user-images.githubusercontent.com/51286963/112282572-953cbc00-8cca-11eb-8117-76d52a0f9875.png"> | <img width="250" src="https://user-images.githubusercontent.com/51286963/112282640-9ff75100-8cca-11eb-9caa-dc56df151dc9.png"> 

## 레퍼런스  
https://www.vadimbulavin.com/collection-view-cells-self-sizing/

## 전달할 내용, personal feedback  
- 경우의 수를 모두 생각하는게 어려웠습니다.. 너무 오래걸려서 미안해요ㅠ.ㅠ mvvm은 아직 미숙해서 조금 적용해봤는데 더 적용할 수 있는 부분이 있다면 피드백 해주세요>_<

2021-03-25 03:36 UTC, minseungseon approved these changes
역시 갓민희입니다!!! cell 도 두개여서 엄청 복잡했을 텐데 너무 고생하셨습니당

2021-03-25 03:36 UTC, minseungseon commented on WeekFlex/WeekFlex/Screen/todoList/Cell/CategoryCell.swift
> +
와.. 감탄합니다
일단 willSet 항상 써보고 싶었는데.. 너무 좋은 예제같습니다ㅠㅠ
newValue 는 무엇인가요?? 궁금합니다 🤔

2021-03-25 03:36 UTC, minseungseon commented on WeekFlex/WeekFlex/Screen/todoList/Cell/RoutineCell.swift
> +        }
오 이런식으로 viewModel 을 통해 cell 설정도 바꿔줄 수 있겠네요 🙌🙌

2021-03-25 03:36 UTC, minseungseon commented on WeekFlex/WeekFlex/Screen/todoList/ViewModel/CategoryCollectionViewCellViewModel.swift
> +    var categoryColor: String? { get }}
}} -> typo 난 것 같습니닷 !! 🤭

2021-03-25 06:50 UTC, xwoud commented on WeekFlex/WeekFlex/Screen/todoList/Cell/CategoryCell.swift
> +
먼저 willSet은 ```프로퍼티 옵저버```로 값이 변경된 직후를 감지하는 역할입니다! 'ㅅ'( 비슷한 것으로 didSet이 있는데, 이건 값이 변경되기 직전을 감지 ! )
Cell에서 isSelected는 Cell이 선택되었는지를 현지 true, false로 반환해주고 있는데 이 때 cell의 isSelected 값이 바뀌면 willSet이 감지를 해줍니다 ! newValue는 저 안에서 사용할 수 있는 ```매개변수```입니다 ! 
``` nameLabel.textColor = newValue ? UIColor.black : .gray4 ```를 예시로 들어보자면
nameLabel.textColor = newValue라는 변수를 지정을 해주는 것이고 newValue는 black과 gray4의 색을 왔다갔다 해주는것이죠!( 현재 값이 black 이면 newValue에는 gray4가 할당이되고, 현재 값이 gray4면 newValue에는 black이 할당되는...! ) 

저는 처음 저 collectionView의 Cell이 만들어질 때 gray4값을 기본값으로 주었는데 , 그럼 isSelected == false 일 때 gray4라는 컬러를 가지고 있고, 만약 제가 하나의 셀을 클릭을 해서 isSelected == true가 된다면, 저 willSet이 호출이 되어서 gray4이니깐 newValue는 Black이 되어서 선택한 셀의 라벨이 진하게 표시가 되게 만들었습니다 ! 
좀 횡설수설 한거같은데.. 이해가 됬으면 좋겠습니당 ㅎㅎ💗

2021-03-25 07:07 UTC, minseungseon requested changes
리뷰 추가했습니다!

2021-03-25 07:07 UTC, minseungseon commented on WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
> +
줄바꿈 한줄로 줄여도 될 것 같습니다!! 👀

2021-03-25 07:07 UTC, minseungseon commented on WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
> +    }
오.. flowLayout 을 IBOutlet 으로 뺄 수 있는지 전혀 몰랐네요...? 
한수 배우고 갑니당...
여기 위에랑 안에 부분 줄바꿈 정리해야할 것 같아요!!! 
한꺼번에 줄바꿈같은거 정리하는 단축키가 있긴 합니다만 혹시 아시려나요???? ( control + i )

2021-03-25 07:07 UTC, minseungseon commented on WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
> +            // 자동을 첫번째 카테고리 선택하기
ㅋㅋㅋㅋㅋ typo!! 자동을 --> 자동으로... ㅎㅎ... 그냥... 눈에보여서 .. 알려드립니당 푸핳... ㅠ

2021-03-25 07:07 UTC, minseungseon commented on WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
> +        textField.becomeFirstResponder()
오 `.becomeFirstResponder()` 는 왜 들어간건가요?? 궁금합니닷!!

2021-03-25 07:07 UTC, minseungseon commented on WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
> +                // 선택한 카테고리로 필터링
필터링 함수 신기하네요... 
결국 searchBox 인가 안쓰고 textField로 처리한거죵???

2021-03-25 07:07 UTC, minseungseon commented on WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
> +                // 검색중이라면?
근데 이 searchText != nil 은 한글자 한글자 쓸 때 마다 확인이 되는건가요??

2021-03-25 07:07 UTC, minseungseon commented on WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
> +    }
func 함수 이름이 오타가 난 것 같습니다??

2021-03-25 07:09 UTC, xwoud commented on WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
> +                // 선택한 카테고리로 필터링
넹 맞어요! searchBar를 쓰지 않은 이유는 이중으로 CollectionView가 들어가야하는 상황이였고, Custom을 하는데 한계가 있기 때문에 직접 구현했습니다 ㅎㅎ

2021-03-25 07:15 UTC, xwoud commented on WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
> +                // 검색중이라면?
음 ~ 일단 105번째 줄에 ```  searchTextField.addTarget(self, action: #selector(textFieldDidChange(_:)), for: .editingChanged) ``` 코드가 있는데 이게 search를 할 때 textField가 바뀔 때 마다 ```textFieldDidChange ```라는 함수가 실행이 됩니다 !

textFieldDidChange 함수를 보면 ( 151번째 줄 ) ```routineCollectionView.reloadData()```가 있기 때문에 한글자 한글자 쓸 때 마다 검사가 되는 방식이 맞다고 할 수 있을거같아요!

2021-03-25 07:16 UTC, xwoud commented on WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
> +        textField.becomeFirstResponder()
```becomeFirstResponder```는 키보드를 자동으로 위로 떠오르게끔 해줍니다 ! ㅎㅎ

2021-03-25 14:52 UTC, merged

2021-03-29 10:43 UTC, kacey0416 commented on WeekFlex/WeekFlex/Screen/todoList/Cell/CategoryCell.swift
> +
헉 완전 이해쏙쏙입니다요 뭔가 적용할 수 있는 곳 많을 거 같은데 나중에 비슷한 방법으로 써봐도 될까요..!!

2021-03-29 10:43 UTC, kacey0416 commented on WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
> +            // 동적 사이즈를 주기 위해 estimatedItemSize 를 사용했다. 대략적인 셀의 크기를 먼저 조정한 후에 셀이 나중에 AutoLayout 될 때, 셀의 크기가 변경된다면 그 값이 다시 UICollectionViewFlowLayout에 전달되어 최종 사이즈가 결정되게 된다.
오 동적사이즈 조절할때 이렇게도 쓸수있군요!!

2021-03-29 10:43 UTC, kacey0416 commented on WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
> +            searchText = textField.text
입력창에 검색어가 입력돼있을때 카테고리콜렉션을 안 보이게 하는 코드는 어디에 있나용??

2021-03-29 12:39 UTC, xwoud commented on WeekFlex/WeekFlex/Screen/todoList/Cell/CategoryCell.swift
> +
@adfilm2  당연하져... 새로운거 함께 계속 도전합시다~!

2021-03-29 12:40 UTC, xwoud commented on WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
> +            searchText = textField.text
@adfilm2 사실 그거 그냥 Hidden으로 해주면 되는데.. 공간이 비어서 너무 안예쁜거같아서 카테고리 살릴 수 있냐고 물어봤어요!!